name: Build Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Đăng nhập vào DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build và push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./complete        # Đặt context là thư mục chứa Dockerfile
          file: ./complete/Dockerfile # Đặt đúng đường dẫn đến Dockerfile trong thư mục con
          push: true
          tags: yourdockerhubusername/my-app:latest
